import = ["catppuccin/catppuccin-mocha.toml"]

[font]
size = 20

[font.bold]
family = "JetbrainsMono NF"

[font.bold_italic]
family = "JetbrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono NF"
style = "Italic"

[font.normal]
family = "JetbrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"
